services:
  - type: web
    name: metabase
    env: docker
    plan: starter-plus
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx1024m
    ports:
      - port: 3000
    healthCheckPath: /
